amcl:
  ros__parameters:
    use_sim_time: True
    base_frame_id: "base_link"
    odom_frame_id: "odom"
    scan_topic: "scan"
    min_particle_num: 500
    max_particle_num: 2000
    # Other AMCL parameters...

controller_server:
  ros__parameters:
    use_sim_time: True
    # Controller parameters...

planner_server:
  ros__parameters:
    use_sim_time: True
    # Planner parameters...

behavior_server:
  ros__parameters:
    use_sim_time: True
    # Behavior parameters...

bt_navigator:
  ros__parameters:
    use_sim_time: True
    # BT Navigator parameters...

lifecycle_manager:
  ros__parameters:
    use_sim_time: True
    autostart: True
    node_names:
      - "controller_server"
      - "planner_server"
      - "behavior_server"
      - "bt_navigator"
      - "amcl"
      - "map_server"
